# Generated by Django 2.1.15 on 2021-11-20 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0003_auto_20211115_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='subject_pics')),
                ('description', models.CharField(max_length=100)),
                ('teacher', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'subjects',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profiles'},
        ),
        migrations.AddField(
            model_name='student',
            name='subject1',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_1', to='learn.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject2',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_2', to='learn.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject3',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_3', to='learn.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject4',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_4', to='learn.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject5',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_5', to='learn.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject6',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_6', to='learn.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject7',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_7', to='learn.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject8',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_8', to='learn.Subject'),
        ),
    ]
