# Generated by Django 2.1.15 on 2021-11-20 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20211120_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject1',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject2',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject3',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject4',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject4', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject5',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject5', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject6',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject6', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject7',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject7', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject8',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject8', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
