# Generated by Django 2.1.15 on 2021-11-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20211120_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject1',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_1', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject2',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_2', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject3',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_3', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject4',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_4', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject5',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_5', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject6',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_6', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject7',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_7', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject8',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_8', to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
