# Generated by Django 2.1.15 on 2021-11-21 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_auto_20211120_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject7',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject8',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
