# Generated by Django 2.1.15 on 2021-11-21 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_auto_20211121_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Subject'),
        ),
    ]
